api_platform:
    title: Bienvenido a la API
    description: 'Esta es la API de la aplicación'
    version: 1.0.0
    formats: 
        json: [ 'application/json' ]
    swagger:
        api_keys: 
            JWT: 
                name: Authorization
                type: header
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
